use ed25519_dalek::{PublicKey, Signature, Verifier};
use std::collections::HashSet;
use std::sync::{Arc, Mutex};
use lazy_static::lazy_static;

lazy_static! {
    /// In-memory cache of burned keys. Ghost nodes.
    static ref QUARANTINE_LIST: Arc<Mutex<HashSet<[u8; 32]>>> = Arc::new(Mutex::new(HashSet::new()));
}

/// A cryptographic kill-switch broadcasted across the mesh.
#[derive(Clone, Debug)]
pub struct BurnNotice {
    /// The Ed25519 Public Key of the compromised/seized device
    pub targeted_pubkey: [u8; 32],
    /// The timestamp of the burn to prevent replay attacks (in reality from P2P-NTP median)
    pub timestamp: u64,
    /// Signature generated by the "Zero Patient" Admin Key (Root CA)
    pub admin_signature: Signature,
}

impl BurnNotice {
    /// Processes an incoming Burn Notice. If valid, excommunicates the node and triggers Viral Propagation.
    pub fn process_notice(notice: &BurnNotice, admin_pubkey: &PublicKey) -> Result<bool, &'static str> {
        // 1. Verify the signature actually belongs to the Admin/Root CA
        let mut msg_bytes = Vec::new();
        msg_bytes.extend_from_slice(&notice.targeted_pubkey);
        msg_bytes.extend_from_slice(&notice.timestamp.to_be_bytes());
        
        if admin_pubkey.verify(&msg_bytes, &notice.admin_signature).is_err() {
            return Err("Burn Notice Signature Invalid! Possible hostile forgery.");
        }

        let mut quarantine = QUARANTINE_LIST.lock().unwrap();
        
        // If already cached, doing nothing avoids infinite broadcast loops
        if quarantine.contains(&notice.targeted_pubkey) {
            return Ok(false); 
        }

        // 2. Excommunication (The Guillotine)
        quarantine.insert(notice.targeted_pubkey);
        println!("[SCORCHED EARTH] Valid Burn Notice received! PubKey `{:?}` has been EXCOMMUNICATED.", notice.targeted_pubkey);

        // 3. Trigger Viral Propagation: In actual pipeline, this tells Mesh Orchestrator
        // to ignore Duty Cycling and max-blast this packet to AWDL/BLE neighbors immediately.
        Ok(true) // True means "We absorbed it, please broadcast it immediately!"
    }

    /// Checks if a given Public Key is currently in the Burn Notice quarantine list.
    pub fn is_quarantined(pubkey: &[u8; 32]) -> bool {
        QUARANTINE_LIST.lock().unwrap().contains(pubkey)
    }
}
